### ISSUE TITLE
Support building without AVX2

### ISSUE THREAD

**Issue by dtolnay** [pikkr/pikkr#14]
Could there be a way to fall back to a slower codepath if AVX2 is not available?

For now this could be a Cargo feature and later it could be detected automatically by https://github.com/rust-lang/rfcs/pull/2045.

**Comment by kjmrknsn** [comment]
Using AVX can be a fallback option. I will investigate how to implement this kind of fallback processing.

**Comment by llogiq** [comment]
Perhaps it helps to take a look how [bytecount](https://github.com/llogiq/bytecount) does it.

**Comment by kjmrknsn** [comment]
Resolved by #65
