### ISSUE TITLE
Benchmarks need to be reproducible

### ISSUE THREAD

**Issue by dtolnay** [pikkr/pikkr#5]
In the readme I see links to the benchmark code and a collection of 5 large JSON datasets, but I can't tell which of those datasets were used, what queries were executed, and what size the training data was. I would need all of these to be able to reproduce the benchmarks.

**Comment by kjmrknsn** [comment]
Thanks for the suggestion. I will add a shell script so that benchmarks are reproducible.

**Comment by dtolnay** [comment]
Thanks. While you are working on the shell script, could you share the details here? All I need is the arguments to pass to `rjpb`.

**Comment by kjmrknsn** [comment]
https://gist.github.com/kjmrknsn/0d7fef8c30d8db7f9720e494f05855b7#gistcomment-2191224 is a sample of benchmark (num of parsed fields = 1)

**Comment by dtolnay** [comment]
Oh nice. Are companies_1g, 2g, 4g, 8g just companies.json concatenated together enough times?

**Comment by kjmrknsn** [comment]
Yes. I'm sorry for the lack of explanation.

**Comment by kjmrknsn** [comment]
```
$ wc -l companies.json
   18801 companies.json
$ wc -l companies_1g.json
  263214 companies_1g.json
$ wc -l companies_2g.json
  526428 companies_2g.json
$ wc -l companies_4g.json
 1052856 companies_4g.json
$ wc -l companies_8g.json
 2105712 companies_8g.json
```
